# Ahora se vincula al listener "http" del Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ruta-para-avatares2
  namespace: avatares
spec:
  parentRefs: 
  - name: gateway-principal
    namespace: nginx-gateway
    sectionName: http   # <<<--- ¡CORREGIDO!
  
  hostnames:
  - "avatares2.chicho.com.ar"
  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: web
      port: 5173