# --- 1. Namespace (Sin cambios) ---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prueba
---
# --- 2. Deployment (Sin cambios) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hello
  namespace: app-prueba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hello
  template:
    metadata:
      labels:
        app: app-hello
    spec:
      containers:
      - name: hello
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
# --- 3. Service (Sin cambios) ---
apiVersion: v1
kind: Service
metadata:
  name: servicio-hello
  namespace: app-prueba
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-hello
---
# --- 4. El Gateway (¡SIMPLIFICADO!) ---
# Ahora solo escucha en HTTP, ya que NGINX Proxy Manager
# se encargará del SSL (HTTPS).
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-principal
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
  # Listener HTTP (puerto 80)
  # Este es el único listener que necesitas.
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
---
# --- 5. La Ruta HTTP (CORREGIDA) ---
# Ahora se vincula al listener "http" del Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ruta-para-hello
  namespace: app-prueba
spec:
  parentRefs: 
  - name: gateway-principal
    namespace: nginx-gateway
    sectionName: http   # <<<--- ¡CORREGIDO!
  
  hostnames:
  - "avatares2.chicho.com.ar"
  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: servicio-hello
      port: 80
