apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
     server: https://acme-staging-v02.api.letsencrypt.org/directory
     email: rubencoria7@gmail.com
     privateKeySecretRef:
       name: letsencrypt-staging
     solvers:
        - http01:
            gatewayHTTPRoute:
              parentRefs:
                - name: gateway-principal
                  namespace: nginx-gateway
                  kind: Gateway
