version: "3"
services:
  api:
    image: chichocoria/avatares-devops-api:64
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
  web:
    image: chichocoria/avatares-devops-web:1
    network_mode: "host"
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
