apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Reemplaza esto con tu token real de Cloudflare
  api-token: aqui_el_token_de_cloudflare