apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared
spec:
  replicas: 2 # Alta disponibilidad
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        imagePullPolicy: IfNotPresent
        args:
        - tunnel
        - --metrics=0.0.0.0:2000
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: token
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 1
          periodSeconds: 10